export type AiMlArchitectureQuestion = {
  title: string;
  prompt: string;
  options: Array<{ id: string; label: string }>;
  correctOptionId: string;
};

const q = (title: string, prompt: string, correct: string, ...wrong: string[]): AiMlArchitectureQuestion => {
  const choices = [{ id: "correct", label: correct }, ...wrong.map((label, index) => ({ id: `wrong-${index + 1}`, label }))];
  let hash = 0;
  for (const character of prompt) hash = (hash * 31 + character.charCodeAt(0)) >>> 0;
  const offset = hash % choices.length;
  return { title, prompt, options: [...choices.slice(offset), ...choices.slice(0, offset)], correctOptionId: "correct" };
};

/** Fifty AI/ML system-design choices across data, serving, retrieval, safety, and evaluation. */
export const AI_ML_ARCHITECTURE_QUESTION_BANK: AiMlArchitectureQuestion[] = [
  // Data, training, and feature systems
  q("Training data source", "A recommender’s training data is assembled from mutable production tables. What architecture makes training runs reproducible?", "Versioned data snapshots with documented lineage into each training run", "Query live tables differently each time", "Keep only the final model file", "Copy data manually to laptops"),
  q("Offline and online features", "A fraud model needs the same feature definitions in batch training and real-time serving. What boundary is most important?", "A shared versioned feature contract with offline and online materializations", "Two independent feature implementations", "A single browser cache", "Only an online feature store"),
  q("Event-time correctness", "Late events arrive after daily model features are computed. What should the pipeline design include?", "Event-time windows, watermarks, and a bounded correction/backfill strategy", "Ignore all late events", "Use arrival time as the only truth", "Retrain after every event"),
  q("Label availability", "The true outcome for a prediction arrives weeks later. What should evaluation architecture retain?", "Prediction-time inputs, model version, and joinable delayed outcome records", "Only current predictions", "The model’s training date", "A UI screenshot"),
  q("Data quality gate", "A key input feed becomes mostly null. What should sit before model serving?", "A data-quality validation and safe fallback or holdout path", "An automatic random-value generator", "A larger model", "A client-side retry"),
  q("Privacy boundary", "Training data contains personal information. What architecture reduces exposure?", "Governed access, minimization, de-identification where appropriate, and auditable use", "One shared raw-data bucket", "Embedding all records in client code", "Unlimited analyst access"),
  q("Feature freshness", "A real-time model depends on features that update at different speeds. What contract must serving know?", "Feature freshness and fallback semantics for each dependency", "Only the feature names", "The GPU type", "The dashboard refresh interval"),
  q("Backfill design", "A new feature must be calculated for historical and live data. What keeps the two paths coherent?", "One versioned transformation with validation across backfill and incremental updates", "Different undocumented formulas", "Live data only", "Historical data only"),
  q("Training isolation", "Several teams share expensive GPU training infrastructure. What architecture prevents noisy-neighbor failures?", "Queued jobs with quotas, priority policy, isolation, and observable scheduling", "First-come work with no limits", "One global admin process", "Run all jobs on developer machines"),
  q("Dataset discoverability", "Teams repeatedly build models from incompatible definitions of the same metric. What platform capability helps?", "A governed catalog with owners, schemas, lineage, and reusable definitions", "More copies of the same CSV", "A shared chat channel", "Untracked notebooks"),
  // Model registry and deployment
  q("Model release artifact", "A production model must be rolled back to the exact prior behavior. What should a registry release reference?", "Immutable model, code, configuration, prompt, and evaluation artifacts", "Only a model nickname", "The latest training notebook", "A deployment screenshot"),
  q("Progressive rollout", "A new classifier has uncertain behavior on rare inputs. What deployment topology reduces risk?", "Shadow or canary traffic with sliced evaluation before expansion", "Immediate global replacement", "Delete the prior model first", "Route only internal tests forever"),
  q("Traffic routing", "Two model versions need an A/B comparison without mixing a user’s experience. What should routing use?", "A stable assignment key with versioned experiment configuration", "A random choice on every request", "The browser’s current tab", "A global mutable flag only"),
  q("Rollback readiness", "A new embedding index is incompatible with the previous model. How should rollback be designed?", "Keep versioned indexes and route each model only to its compatible index", "Mix vectors from both models", "Delete the old index at deploy time", "Use one unversioned collection"),
  q("Multiple model routes", "A product selects a fast or high-quality model depending on request type. What should the gateway own?", "Explicit routing policy, limits, observability, and fallback behavior", "Only the model provider key", "The chat layout", "One random route"),
  q("Safe model loading", "A model-serving fleet can load arbitrary uploaded artifacts. What boundary is required?", "A trusted, validated artifact registry and isolated loading environment", "Loading any file from user storage", "A public shared model folder", "Browser-side model deserialization"),
  q("Prompt release", "Prompts are modified frequently by several people. What makes them deployable artifacts?", "Versioning, review, evaluation linkage, and controlled promotion", "Editing production prompts in place", "Keeping only the newest text", "Embedding prompts in UI labels"),
  q("Provider portability", "A feature may need to move between model providers. What architecture avoids application-wide rewrites?", "A provider adapter boundary with normalized request, policy, and telemetry handling", "Provider calls scattered through UI components", "One hard-coded provider in every service", "Copying all provider SDKs into clients"),
  q("Serving resilience", "One model region fails. What should a high-availability serving design include?", "A tested fallback or failover path aligned to quality and data-residency constraints", "Infinite retries to the failed region", "A larger client timeout", "No monitoring"),
  q("Cost-aware routing", "A cheap model handles simple cases while difficult cases need a stronger model. What design makes this measurable?", "A routing policy with quality thresholds, cost telemetry, and safe escalation", "Always choose the cheapest model", "Always choose the largest model", "Route by user interface theme"),
  // Retrieval and knowledge architecture
  q("Knowledge freshness", "A RAG assistant must reflect policy updates within an hour. What end-to-end design requirement follows?", "A source-to-index freshness pipeline with monitored completion and versioned retrieval", "A weekly manual reindex", "More prompt instructions", "A longer answer limit"),
  q("Tenant isolation", "Several customers use the same retrieval service. What must retrieval enforce?", "Tenant and authorization filters before candidates reach the model context", "A client-side filter after generation", "One shared unrestricted index", "The user’s browser language"),
  q("Hybrid retrieval", "Users ask both exact-ID and semantic questions over documents. What retrieval design may be appropriate?", "Hybrid lexical and vector retrieval with metadata filtering and evaluation", "Vector search only regardless of task", "Keyword search only regardless of task", "A bigger generation model only"),
  q("Document changes", "Documents are edited and deleted after indexing. What index design preserves correctness?", "Stable document/chunk identities with versioning and deletion propagation", "Append every revision forever without metadata", "Ignore deletions", "Only update the UI"),
  q("Citation traceability", "A product must show why an answer was generated. What should the context assembly preserve?", "Links from answer claims to retrieved source versions and chunks", "Only the final prose", "A random document title", "The model temperature"),
  q("No-answer behavior", "A question has no support in the knowledge base. What should the system architecture enable?", "A grounded no-answer path based on retrieval confidence and policy", "Forced generation from model memory", "A random source citation", "More retrieved documents regardless of relevance"),
  q("Injection defense", "Retrieved documents may contain malicious instructions. What is the safe boundary?", "Treat documents as untrusted data and enforce tool/policy controls outside the model", "Let retrieved content override system policy", "Disable retrieval logs", "Give documents direct database access"),
  q("Context budget", "A corpus is too large to send in full with every request. What should the retrieval layer optimize?", "Relevant, diverse, permissioned context within an explicit token budget", "Maximum possible document count", "Only newest documents", "The output font size"),
  q("Index evolution", "A new embedding model improves recall. What migration plan avoids mixed vector spaces?", "Build a parallel versioned index, validate it, then switch traffic deliberately", "Write new vectors into the existing unversioned index", "Delete all old vectors first", "Mix dimensions at query time"),
  q("Retrieval evaluation", "A team optimizes retrieval based only on user anecdotes. What architecture is missing?", "A versioned representative evaluation set with retrieval and answer-quality metrics", "A larger chat window", "More support tickets", "A random query sample only"),
  // Agents, tools, and workflows
  q("Tool authorization", "An agent can call a tool that changes a customer record. Where must authorization be enforced?", "At the server-side tool boundary using the caller’s identity and policy", "In the model prompt only", "In the chat UI only", "By the model’s confidence score"),
  q("Long-running agent", "An agent workflow takes several minutes and can require approval. What should hold its state?", "A durable workflow record with resumable steps and approval states", "One in-memory HTTP request", "A browser timer", "A single model message"),
  q("Human approval", "Certain agent actions need a person’s approval. What should the architecture record?", "Proposed action, supporting evidence, approver, policy result, and final execution", "Only a thumbs-up", "The model name", "A chat emoji"),
  q("Idempotent tools", "An agent retries a payment-related tool after a timeout. What must the tool API support?", "Idempotency keys and a queryable operation status", "A new payment on every retry", "Only a longer timeout", "Best-effort execution without logs"),
  q("Agent loop control", "An agent can call tools recursively. What should the orchestrator enforce?", "Step, time, cost, and retry limits with a safe stop state", "Unlimited looping", "A larger context every iteration", "No tool-result logging"),
  q("Tool result trust", "A tool returns text that looks like instructions to the agent. How should the orchestrator handle it?", "Treat tool output as typed data with policy-controlled interpretation", "Let it replace system instructions", "Concatenate it into the system prompt blindly", "Disable schema validation"),
  q("Async task result", "An agent starts a long document-analysis task. What client contract avoids a hanging request?", "A durable job ID with status and completion notification", "Keep one HTTP request open until finished", "Ask users to refresh randomly", "Store progress in browser memory only"),
  q("Policy version", "An agent’s allowed actions change with policy. What should each execution retain?", "The policy version and decision trace used at execution time", "Only the current policy text", "The agent avatar", "A generic success flag"),
  q("Tool isolation", "A new external tool is unreliable and may exhaust resources. What architecture guard helps?", "Timeouts, concurrency limits, and bulkhead isolation around that tool", "Unlimited parallel calls", "No error handling", "Call it from the browser directly"),
  q("Workflow compensation", "An agent creates a support case then fails to attach required metadata. What workflow pattern helps recovery?", "Durable state with explicit retry or compensating steps", "Assume both writes always succeed", "Delete all workflow history", "Retry the entire system globally"),
  // Evaluation, safety, and observability
  q("Online evaluation", "A model is strong offline but may harm live users. What architecture supports responsible rollout?", "Outcome instrumentation, guardrails, and controlled experiments tied to the release", "Offline score only", "A larger model card", "No production feedback"),
  q("Evaluation slices", "A model serves several languages and regions. What should the evaluation service support?", "Versioned metrics sliced by language, region, task, and risk category", "One global average only", "Only latency charts", "The model’s training date"),
  q("Safety controls", "A generative endpoint may disclose sensitive data. What should sit around the model?", "Data-access controls, policy checks, output safeguards, and auditable traces", "A higher temperature", "An unbounded prompt", "Client-side string matching alone"),
  q("Feedback loop", "Users flag poor model answers. What pipeline turns that into reliable improvement evidence?", "Triage, labeling/quality review, versioned evaluation, and tracked corrective action", "Train on every flag immediately", "Discard flags after reading", "Count flags without examples"),
  q("Explain a decision", "A regulated prediction needs later review. What should an audit architecture retain within policy?", "Model and feature versions, authorized input evidence, output, and decision trace", "Only the final prediction", "The model’s repository name", "A weekly screenshot"),
  q("Detect silent quality loss", "Transport errors are flat, but users increasingly abandon generated results. What observability is required?", "Product outcome and quality-proxy signals alongside system health metrics", "Only HTTP status codes", "Only CPU usage", "The number of deployments"),
  q("Redact telemetry", "Prompt and retrieval traces help debugging but contain private data. What telemetry design is appropriate?", "Minimize/redact sensitive fields with controlled retention and audit access", "Log all raw content forever", "Turn off all tracing", "Share traces in public channels"),
  q("Safety fallback", "A safety service is unavailable. What should the product’s architecture decide in advance?", "Whether to fail closed, use a bounded fallback, or limit capability by risk", "Always continue normally", "Always fabricate a safe label", "Wait forever for the safety service"),
  q("Inference queueing", "Interactive requests and overnight batch inference share GPUs. What design protects interactive latency?", "Separate priority queues or capacity pools with admission control", "One unbounded FIFO queue", "Batch jobs always first", "No traffic classification"),
  q("Regional data rules", "A customer’s data must remain in a specific geography. What does model architecture need?", "Regional data, retrieval, inference, and fallback boundaries that honor residency", "A single global data store", "Client-side location text only", "A random fallback region")
];

export function aiMlArchitectureQuestion(index: number): AiMlArchitectureQuestion | null {
  return AI_ML_ARCHITECTURE_QUESTION_BANK[index] ?? null;
}
