export type AiMlAppliedEngineeringQuestion = {
  title: string;
  prompt: string;
  options: Array<{ id: string; label: string }>;
  correctOptionId: string;
};

const q = (title: string, prompt: string, correct: string, ...wrong: string[]): AiMlAppliedEngineeringQuestion => {
  const choices = [{ id: "correct", label: correct }, ...wrong.map((label, index) => ({ id: `wrong-${index + 1}`, label }))];
  let hash = 0;
  for (const character of prompt) hash = (hash * 31 + character.charCodeAt(0)) >>> 0;
  const offset = hash % choices.length;
  return { title, prompt, options: [...choices.slice(offset), ...choices.slice(0, offset)], correctOptionId: "correct" };
};

/** Fifty AI/ML production decisions: operate models and data safely, not generic web services. */
export const AI_ML_APPLIED_ENGINEERING_QUESTION_BANK: AiMlAppliedEngineeringQuestion[] = [
  // Observe models in production
  q("Investigate a regression", "A new model version lowers successful task completion for one customer segment. What is the best first move?", "Compare the old and new model by that segment, input slice, and outcome", "Roll it out to every segment", "Retrain on all production traffic immediately", "Hide the segment from reporting"),
  q("Separate latency paths", "P95 inference latency doubles, but only for requests with very long context. What should you inspect first?", "Latency segmented by context size, model route, and retrieval path", "Average latency only", "The colour of the client loading state", "Every model parameter at once"),
  q("Detect drift", "A classifier’s predictions shift sharply after a source-system release. What evidence should you collect?", "Input-feature and prediction distributions before and after the release", "Only the number of API calls", "A new training run without inspection", "The current model filename"),
  q("Trace an answer", "A RAG answer is confidently wrong. What makes the incident diagnosable?", "A trace linking request, retrieval results, prompt version, model version, and answer", "Only the final answer text", "A screenshot of the chat", "More verbose client logs only"),
  q("Monitor a threshold", "A fraud threshold is changed in production. Which signal best validates it?", "False-positive and false-negative outcomes against the agreed business cost", "Overall request volume", "GPU utilization alone", "The number of feature flags"),
  q("Inspect fallbacks", "A model provider intermittently fails. What should monitoring distinguish?", "Primary-model failures, fallback use, fallback quality, and user impact", "Only total success rate", "The provider’s status page colour", "The browser version"),
  q("Watch retrieval freshness", "A knowledge-base refresh completes, yet answers cite old policy. What should be visible?", "Source version, indexing completion, and retrieval freshness for each answer", "Only document upload count", "The prompt length", "A new chat icon"),
  q("Slice safety", "A safety filter seems to block harmless medical-language requests. What is the useful next analysis?", "Review false positives by task, language, and policy category", "Disable all filtering", "Accept the aggregate pass rate", "Increase generation temperature"),
  q("Validate a canary", "A model canary is serving 5% of requests. What should decide expansion?", "Predefined quality, safety, latency, and cost comparisons with the control", "A single impressive example", "The newest model’s benchmark score only", "Whether the deployment was fast"),
  q("Measure abstention", "A model is allowed to defer uncertain cases to a human. What should the team measure?", "Deferral rate, quality of deferred cases, review time, and missed-risk outcomes", "Only the number of humans online", "The model file size", "Total request count"),
  // Data and features
  q("Protect feature parity", "A feature is calculated differently in training and serving. What prevents this recurring?", "A versioned shared feature definition with validation in both paths", "Manual reimplementation in each service", "Training with more epochs", "Removing feature tests"),
  q("Handle missing online data", "A real-time feature is unavailable for some requests. What should serving do?", "Use a documented fallback, record the condition, and monitor its impact", "Invent a random value", "Silently drop the request", "Reuse the previous user’s value"),
  q("Detect bad labels", "A labeling vendor changes its guidelines and training quality drops. What should you check?", "Label distributions, agreement samples, and the guideline/version boundary", "Only the row count", "Inference latency", "The model’s release date"),
  q("Safe backfill", "You need to recompute embeddings for millions of documents. What makes the job safe to resume?", "Versioned embeddings with checkpointed, idempotent writes", "Overwrite every vector without tracking", "Run it as one unmonitored request", "Mix old and new vector spaces"),
  q("Preserve lineage", "An offline feature unexpectedly changes a model’s behavior. What should let you trace it?", "Lineage from model release to feature code, data snapshot, and transformation version", "Only the final metric", "A chat message from the deployer", "The deployment time alone"),
  q("Guard freshness", "A batch prediction is two days stale but still being consumed. What should the system expose?", "Prediction timestamp and a freshness contract that consumers can enforce", "Only the model name", "A longer cache TTL", "The number of records processed"),
  q("Validate schema", "A feature source adds a nullable field used by a model. What should happen before it reaches serving?", "Validate the contract and measure null or unexpected-value rates", "Assume all values are valid", "Discard all historical data", "Raise the model temperature"),
  q("Prevent leakage", "A new feature is available only after an event that occurs after prediction time. What is the right action?", "Exclude it from training and serving because it leaks future information", "Use it only during training", "Use it only for high-value users", "Hide it from the feature registry"),
  q("Inspect sampled data", "A data-quality alert says a feature’s values are out of range. What is a sound response?", "Quarantine or fall back safely while inspecting representative input samples", "Ignore it until retraining", "Clip every value without recording it", "Delete the alert"),
  q("Version feedback", "Human reviewers correct generated answers. What makes their feedback usable later?", "Store reviewed outcomes with task, policy, and data-version context", "Train immediately on anonymous raw clicks", "Keep only an aggregate thumbs-up count", "Discard disagreements"),
  // Release and reproducibility
  q("Reproducible release", "A model behaves differently from its offline evaluation. What release record is essential?", "Model, code, prompt, data/evaluation snapshot, configuration, and environment versions", "The model nickname only", "A link to the launch announcement", "The last training timestamp only"),
  q("Roll back safely", "A prompt update creates unsafe answers. What makes a rollback quick and reliable?", "Immutable prompt/version artifacts with a tested traffic rollback path", "Editing production text in place", "Waiting for the next model training cycle", "Deleting the bad responses first"),
  q("Avoid confounded experiments", "A release changes the model, retriever, and prompt together. What is the main problem?", "You cannot attribute an observed change to one component", "The release has too many files", "The model will always be slower", "The UI cannot render it"),
  q("Promote a model", "What should a production-model promotion gate require?", "Defined evaluations, safety checks, operational checks, and accountable approval", "That it is newer than the current model", "Only a successful build", "The largest parameter count"),
  q("Test rollback data", "A new embedding model requires a new index. What release plan avoids a broken rollback?", "Keep versioned indexes and route traffic deliberately during migration", "Replace the old index immediately", "Mix vectors from both models", "Delete source documents after indexing"),
  q("Stage a provider change", "You are moving inference to a new provider. What should a shadow phase compare?", "Output quality, safety, latency, failure rate, and cost on comparable traffic", "Only provider price", "Only total response length", "The provider’s branding"),
  q("Release a tool", "An LLM agent gets access to a new action. What should be tested before broad rollout?", "Authorized action cases, denial cases, malformed inputs, and recovery behavior", "Only happy-path prompts", "The agent’s greeting", "Whether it can call the tool quickly"),
  q("Keep an eval set honest", "A team repeatedly tunes against one evaluation set. What risk grows over time?", "Overfitting decisions to the benchmark instead of general performance", "The model becomes impossible to deploy", "The data set gets smaller automatically", "Latency disappears"),
  q("Retain artifacts", "An audit asks why a model made a decision last month. What should be retained within policy?", "The release artifact, input/evidence context, and decision trace", "Only today’s model version", "A dashboard screenshot", "The model’s source repository URL"),
  q("Contain a bad release", "A high-severity model defect is confirmed. What is the best first operational response?", "Stop or restrict the affected route, preserve evidence, and use a safe fallback", "Continue collecting more affected examples", "Retrain while leaving it fully live", "Delete the model logs"),
  // Reliability, cost, and capacity
  q("Bound agent loops", "An agent repeats the same tool call after a tool error. What guard is needed?", "Step limits, loop detection, and a visible fail-safe outcome", "Unlimited retries", "A longer tool description", "A larger context window only"),
  q("Avoid overload", "Traffic spikes and the inference queue grows quickly. What protects critical requests?", "Admission control, priority queues, and bounded work with graceful degradation", "Accept every request until workers crash", "Disable queue metrics", "Make retrieval synchronous"),
  q("Control context cost", "Token costs rise because every request includes a large document bundle. What should be optimized first?", "Retrieval selection and context budgets while preserving needed evidence", "Always include more documents", "Increase output length", "Disable response caching"),
  q("Protect GPUs", "One tenant sends unusually large batch jobs and starves interactive inference. What boundary helps?", "Tenant-aware quotas or isolated queues for batch and interactive work", "Run all work in one FIFO queue", "Give that tenant unlimited priority", "Disable interactive traffic"),
  q("Handle cold starts", "A rarely used model route has slow first responses. What is a responsible approach?", "Measure cold-start impact and use warm capacity only where its cost is justified", "Keep every model permanently hot without measurement", "Hide the first response", "Increase prompt length"),
  q("Cache carefully", "Identical retrieval questions arrive often, but source documents change. What makes caching safe?", "Key the cache to source/index version with bounded freshness", "Cache answers forever", "Cache without tracking tenant or authorization", "Disable source updates"),
  q("Set timeouts", "A tool-using agent waits indefinitely for one dependency. What should its tool boundary enforce?", "A bounded timeout with a recoverable fallback or user-visible state", "No timeout", "An immediate retry loop", "A larger token budget"),
  q("Plan capacity", "A launch will double requests to a GPU-backed service. What should planning use?", "Traffic forecast, latency targets, model throughput, and failure headroom", "Only average GPU usage", "Last month’s request count", "The number of engineers on call"),
  q("Manage a queue", "Offline embedding jobs keep retrying a malformed document. What should happen?", "Move it to a diagnosable dead-letter path after bounded retries", "Retry it forever", "Delete it without a record", "Block all other jobs"),
  q("Preserve multi-tenant privacy", "A response cache could return one tenant’s answer context to another. What must the cache key include?", "Tenant and authorization boundary, plus relevant source/version context", "Only the query text", "Only the model name", "The browser session title"),
  // Safety and human operations
  q("Gate risky actions", "An agent proposes issuing a refund. What must decide whether it executes?", "Server-side authorization and policy validation, not the model’s confidence", "The model’s wording", "A higher temperature", "The user interface colour"),
  q("Escalate uncertainty", "A medical-support assistant is uncertain about a high-risk request. What should the product do?", "Use a defined escalation or safe-refusal path with clear user guidance", "Generate a confident answer anyway", "Repeat the prompt", "Silently end the conversation"),
  q("Review policy changes", "A safety policy is updated. What should happen before deployment?", "Run a versioned regression suite including policy-relevant edge cases", "Change the policy text live", "Check one example", "Only validate latency"),
  q("Limit data access", "A retrieval agent can access several internal document sets. What should determine each request’s scope?", "The caller’s authorization and the resource’s access policy", "The model’s guessed need", "The largest available corpus", "The last user’s permissions"),
  q("Redact traces", "Production traces are needed for debugging, but inputs may contain sensitive data. What is the right design?", "Redact or minimize sensitive fields with controlled, auditable access", "Store all raw data in public logs", "Turn off all tracing", "Keep only the model name"),
  q("Respond to feedback", "Users report harmful answers that were not caught by automated checks. What is the first programmatic step?", "Triage examples into a labeled safety-evaluation and incident workflow", "Dismiss reports without examples", "Disable user feedback", "Raise the answer length limit"),
  q("Audit tool use", "A regulated workflow lets an agent take external actions. What must every action record?", "Actor, authorized intent, inputs, policy decision, result, and time", "Only that a model was used", "The action title", "A random request ID"),
  q("Preserve multi-tenant privacy", "A response cache could return one tenant’s answer context to another. What must the cache key include?", "Tenant and authorization boundary, plus relevant source/version context", "Only the query text", "Only the model name", "The browser session title"),
  q("Detect a silent failure", "The model service returns 200 responses but empty useful answers. What should alerting track?", "Outcome-quality or fallback-rate signals, not transport success alone", "Only HTTP status", "Only container health", "The number of requests"),
  q("Verify a recovery", "A provider outage ends. What should happen before returning all traffic to the primary?", "Gradually restore traffic while verifying latency, errors, quality, and cost", "Switch all traffic instantly without checks", "Delete fallback metrics", "Keep the fallback forever without review")
];

export function aiMlAppliedEngineeringQuestion(index: number): AiMlAppliedEngineeringQuestion | null {
  return AI_ML_APPLIED_ENGINEERING_QUESTION_BANK[index] ?? null;
}
