// Generated by scripts/generate-teacher-greetings.ts. Do not edit by hand.
// Regenerate with `pnpm voice:greetings` after changing a greeting or voice.

export type GreetingAudio = { text: string; voice: string; style: string; src: string };

export const GREETING_AUDIO: Readonly<Record<string, GreetingAudio>> = {
  "maya": {
    "text": "Hi, I'm Maya. Tell me what you're working toward, and I'll help you turn each difficult topic into a clear next step.",
    "voice": "Aoede",
    "style": "teacher-natural-v1",
    "src": "/voice/greetings/maya-028c9549f037.wav"
  }
};
