// Generated by scripts/generate-static-voice.mts. Do not edit by hand.
// Regenerate with `pnpm voice:lines` after changing a line, greeting, or voice.

export type StaticVoiceLine = {
  persona: string;
  text: string;
  voice: string;
  style: string;
  src: string;
};

export const STATIC_VOICE_LINES: readonly StaticVoiceLine[] = [
  {
    persona: "alex",
    text: "Hi, I'm Alex. We'll identify what matters most, test your reasoning, and build a practical plan you can trust.",
    voice: "Schedar",
    style: "teacher-natural-v1",
    src: "/voice/alex-47aa8e81354f.mp3"
  },
  {
    persona: "claire",
    text: "Hi, I'm Claire. Take your time explaining your approach. I'll listen closely, then ask the questions that help you strengthen it.",
    voice: "Kore",
    style: "teacher-natural-v1",
    src: "/voice/claire-4d1dade23433.mp3"
  },
  {
    persona: "daniel",
    text: "Hi, I'm Daniel. We'll slow difficult ideas down, work through them together, and make sure you understand why the answer works.",
    voice: "Iapetus",
    style: "teacher-natural-v1",
    src: "/voice/daniel-9fde96cec8e3.mp3"
  },
  {
    persona: "james",
    text: "Good to meet you. I'm James. We'll work through the interview in a clear order, one question at a time, so you always know what to focus on.",
    voice: "Charon",
    style: "teacher-natural-v1",
    src: "/voice/james-42a7dff3c885.mp3"
  },
  {
    persona: "maya",
    text: "Hi, I'm Maya. Tell me what you're working toward, and I'll help you turn each difficult topic into a clear next step.",
    voice: "Aoede",
    style: "teacher-natural-v1",
    src: "/voice/maya-028c9549f037.mp3"
  },
  {
    persona: "olivia",
    text: "Hi, I'm Olivia. We'll practise through a natural conversation, so you can become clearer and more confident without sounding rehearsed.",
    voice: "Vindemiatrix",
    style: "teacher-natural-v1",
    src: "/voice/olivia-a590e811556c.mp3"
  },
  {
    persona: "ryan",
    text: "Hi, I'm Ryan. I'll challenge unclear assumptions, tighten your reasoning, and help you communicate your strongest answer with confidence.",
    voice: "Orus",
    style: "teacher-natural-v1",
    src: "/voice/ryan-b71928205dff.mp3"
  },
  {
    persona: "sophia",
    text: "Hi, I'm Sophia. Share how you would approach the problem, and I'll help you make the reasoning precise, structured, and easy to defend.",
    voice: "Sulafat",
    style: "teacher-natural-v1",
    src: "/voice/sophia-2df2164a353a.mp3"
  }
];
