/**
 * Pre-generates each teacher's fixed greeting as a static file so onboarding
 * plays it from the CDN instead of waiting for live text-to-speech.
 *
 *   pnpm voice:greetings          # generate missing or changed greetings
 *   pnpm voice:greetings --force  # regenerate every greeting
 *
 * Writes public/voice/greetings/<persona>-<hash>.wav and the manifest
 * src/lib/avatars/greeting-audio.generated.ts. Commit both.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ALL_PERSONAS, type InterviewerPersona } from "../src/lib/avatars/personas";
import { GREETING_AUDIO } from "../src/lib/avatars/greeting-audio.generated";
import {
  GEMINI_TTS_MODEL,
  GEMINI_TTS_STYLE_VERSION,
  synthesizeGemini
} from "../src/server/voice/gemini-speech";

const OUTPUT_DIRECTORY = join("public", "voice", "greetings");
const MANIFEST_PATH = join("src", "lib", "avatars", "greeting-audio.generated.ts");
const force = process.argv.includes("--force");

type Entry = { text: string; voice: string; style: string; src: string };

function fingerprint(persona: InterviewerPersona): string {
  return createHash("sha256")
    .update(
      JSON.stringify([
        GEMINI_TTS_STYLE_VERSION,
        GEMINI_TTS_MODEL,
        persona.geminiVoice,
        persona.id,
        persona.greeting
      ])
    )
    .digest("hex")
    .slice(0, 12);
}

function isCurrent(persona: InterviewerPersona, entry: Entry | undefined): entry is Entry {
  return Boolean(
    entry &&
    entry.text === persona.greeting &&
    entry.voice === persona.geminiVoice &&
    entry.style === GEMINI_TTS_STYLE_VERSION &&
    existsSync(join("public", entry.src))
  );
}

async function synthesizeWithRetry(persona: InterviewerPersona, apiKey: string) {
  for (let attempt = 1; ; attempt += 1) {
    try {
      return await synthesizeGemini({ text: persona.greeting, apiKey, persona });
    } catch (error) {
      if (attempt >= 2) throw error;
      const waitMs = 10_000;
      process.stdout.write(
        `  ${persona.id}: attempt ${attempt} failed, retrying in ${waitMs / 1000}s\n`
      );
      await new Promise((resolve) => setTimeout(resolve, waitMs));
    }
  }
}

async function main(): Promise<void> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY is required to generate greetings.");
  mkdirSync(OUTPUT_DIRECTORY, { recursive: true });

  const existing = GREETING_AUDIO as Readonly<Record<string, Entry>>;
  // Start from the saved manifest so a run stopped by quota keeps prior work.
  const manifest: Record<string, Entry> = { ...existing };
  let generated = 0;
  let failed = 0;
  for (const persona of ALL_PERSONAS.filter((candidate) => candidate.greeting.trim())) {
    const previous = existing[persona.id];
    if (!force && isCurrent(persona, previous)) {
      process.stdout.write(`  ${persona.id}: current\n`);
      continue;
    }
    const fileName = `${persona.id}-${fingerprint(persona)}.wav`;
    const entry: Entry = {
      text: persona.greeting,
      voice: persona.geminiVoice,
      style: GEMINI_TTS_STYLE_VERSION,
      src: `/voice/greetings/${fileName}`
    };
    // A file named for this exact fingerprint was generated by an earlier run.
    if (!force && existsSync(join(OUTPUT_DIRECTORY, fileName))) {
      manifest[persona.id] = entry;
      writeManifest(manifest);
      process.stdout.write(`  ${persona.id}: adopted ${fileName}\n`);
      continue;
    }
    let audio;
    try {
      audio = await synthesizeWithRetry(persona, apiKey);
    } catch (error) {
      failed += 1;
      process.stdout.write(
        `  ${persona.id}: skipped (${error instanceof Error ? error.message : String(error)})\n`
      );
      continue;
    }
    if (audio.contentType !== "audio/wav") {
      throw new Error(`${persona.id}: unexpected audio type ${audio.contentType}`);
    }
    // Remove this persona's superseded files so stale audio is never served.
    for (const stale of readdirSync(OUTPUT_DIRECTORY)) {
      if (stale.startsWith(`${persona.id}-`) && stale !== fileName) {
        rmSync(join(OUTPUT_DIRECTORY, stale));
      }
    }
    writeFileSync(join(OUTPUT_DIRECTORY, fileName), audio.bytes);
    manifest[persona.id] = entry;
    writeManifest(manifest);
    generated += 1;
    process.stdout.write(
      `  ${persona.id}: generated ${fileName} (${Math.round(audio.bytes.byteLength / 1024)} KB)\n`
    );
  }
  writeManifest(manifest);
  process.stdout.write(
    `${Object.keys(manifest).length} greetings in the manifest; ${generated} generated, ${failed} skipped.\n`
  );
  if (failed) process.exitCode = 1;
}

function writeManifest(manifest: Record<string, Entry>): void {
  writeFileSync(
    MANIFEST_PATH,
    `// Generated by scripts/generate-teacher-greetings.ts. Do not edit by hand.
// Regenerate with \`pnpm voice:greetings\` after changing a greeting or voice.

export type GreetingAudio = { text: string; voice: string; style: string; src: string };

export const GREETING_AUDIO: Readonly<Record<string, GreetingAudio>> = ${JSON.stringify(manifest, null, 2)};
`
  );
}

void main().catch((error: unknown) => {
  process.stderr.write(
    `Greeting generation failed: ${error instanceof Error ? error.message : String(error)}\n`
  );
  process.exitCode = 1;
});
